services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: test_fastapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - db_data:/var/lib/postgresql/dockerimage

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

# volumes:
#   db_data: